### ISSUE TITLE
Can a replacing decoration generate a string instead of an HTMLElement

### ISSUE THREAD

**Issue by talengu** [jffaust/boundless#4]
Hi, 

I see you QAs in [codemirror](https://discuss.codemirror.net/t/can-a-replacing-decoration-generate-a-string-instead-of-an-htmlelement/4146/2)

I run into the same question as you. obsidian does not support `<img src=local img>`  in live preview.
I want to replace the **img link** from `build_blog/image-20181112002650646.png` to `app://local/D:/git/blog_source/_posts/build_blog/image-20181112002650646.png`

I made a easy plugin . It  only support in the reading view now. TODO: support live preview mode
https://github.com/talengu/obsidian-local-img-plugin/blob/master/main.ts

**Can you share some info about your obsidian plugin?** It is lost in public now.

https://github.com/jffaust/obsidian-variables

**Comment by jffaust** [comment]
@talengu I've put it back in public but I was never able to make it work with Live Preview for images.
